config/routes.rb
Dias::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :projects
  

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  resources :users do
    member do
      get :follow
      get :unfollow
    end
  end

  resources :projects do
    member do
      get :follow
      get :unfollow
    end
  end
  

  get "about" => "pages#about"
  get "faq" => "pages#faq"
  get "team" => "pages#team"
  get "partners" => "pages#partners"
  get "manifesto" => "pages#manifesto"
  get "membership" => "pages#membership"
  get "fonctionnement" => "pages#fonctionnement"
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :projects
	acts_as_follower
	acts_as_followable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :default_url => ":style/missing_avatar.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  #validates :first_name, presence: true
  #validates :last_name, presence: true
  #validates :birth_date, presence: true
  #validates :birth_place, presence: true
  #validates :pays, presence: true
  #validates :address, presence: true
  #validates :phone, presence: true
  #validates :skype, presence: true
  #validates :contribution, presence: true

  CONTRIBUTION_FREQUENCIES = ["mensuelle", "trimestrielle", "annuelle"]
  GENDERS = ["feminin", "masculin"]

  def name_or_fullname
  	name.present? ? name : "#{first_name} #{last_name}"
  end

  def saldo
    if total_contribution
      total_contribution - global_funding
    else
      0
    end
  end

  def global_funding
    global_funding = 0
    following_projects.each do |project|
      global_funding += project.funding.to_i
    end
    global_funding
  end

  def nonvalidated
    !validated
  end

  def self.contribution_frequencies
    CONTRIBUTION_FREQUENCIES.map do |contribution_frequency|
      [I18n.t("contribution_frequencies.#{contribution_frequency}"), contribution_frequency]
    end
  end

  def self.genders
    GENDERS.map do |gender|
      [I18n.t("genders.#{gender}"), gender]
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @project = @user.projects
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
    redirect_to :back
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.stop_following(@user)
    redirect_to :back
  end


  def edit
  	@user = current_user
    @contribution_frequencies = User.contribution_frequencies
    @genders = User.genders
  end

  def update
  	@user = User.find(params[:id])
    @contribution_frequencies = User.contribution_frequencies
    @genders = User.genders
    if @user.update(user_params)
      redirect_to @user, notice: "Votre profil a bien ete mis a jour"
    else
      render action: "edit", notice: "Oups, veuillez reessayer"
    end
  end

  def user_params
    params.require(:user).permit(:email, :name, :first_name, :last_name, :birth_date, :birth_place,
                                  :pays, :address,
    															:prefix, :phone, :skype,
															    :membership, :skills,
															    :contribution, :contribution_frequency, :total_contribution,
                                  :director, :avatar, :gender)
  end

end

app/views/users/edit.html.erb
<div class="page-header">
    <h1>Editez votre profil</h1>

<div class="alert alert-info alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <p><strong>Attention !</strong> Les champs marqués d'un astérisque (<span class="diasred">*</span>) doivent être remplis</p>
</div>

</div>






  <%= simple_form_for(@user, :url => user_path, :html => { :multipart => true }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
<p class="lead">Vous</p>
    <div class="row">
      

      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :first_name, "Votre prénom" %><span class="diasred"> (*)</span>
          <%= f.text_field :first_name, class: 'form-control input-lg' %>
        </div>
      </div>

      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :last_name, "Votre nom" %><span class="diasred"> (*)</span>
          <%= f.text_field :last_name, class: 'form-control input-lg' %>
        </div>
      </div>

      <div class="col-md-4 form-group">
      <%= f.label :gender, "Votre sexe" %><span class="diasred"> (*)</span>
      <%= f.select :gender, @genders, {:selected => params[:gender]}, {class: "form-control input-lg"} %>
    
    </div>

      
    </div>


    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :avatar, "Ajoutez votre photo de profil" %>
          <%= f.file_field :avatar, class: "form-control input-lg" %>
        </div>
      </div>

      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :birth_place, "Votre lieu de naissance" %>
          <%= f.text_field :birth_place, class: 'form-control input-lg' %>
        </div>
      </div>

      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :birth_date, "Votre date de naissance" %><span class="diasred"> (*)</span>
          <br><%= f.date_select :birth_date, start_year: 1930, :order => [:day,:month,:year], class: 'form-control input-lg' %>
        </div>
      </div>
    </div>

<p class="lead">Vos coordonnées <br><small>(ne seront pas publiées sur votre profil)</small></p>
<div class="row">
  <div class="col-md-3">
    <div class="form-group">
      <%= f.label :pays, "Votre ville de résidence" %><span class="diasred"> (*)</span>
      <%= f.text_field :pays, class: 'form-control input-lg' %>
    </div>
  </div>

  <div class="col-md-3">
    <div class="form-group">
      <%= f.label :address, "Votre adresse officielle" %>
      <%= f.text_field :address, class: 'form-control input-lg' %>
    </div>
  </div>

   <div class="col-md-3">
    <%= f.label :phone , "Votre numéro de téléphone" %>
    <div class="row">
      <div class="col-md-5">
        <div class="form-group">
          <div class="input-group"><span class="input-group-addon">+</span>
          <%= f.text_field :prefix, class: 'form-control input-lg', :placeholder => "32" %></div>
        </div>
      </div>
      <div class="col-md-7">
        <div class="form-group">
          <%= f.text_field :phone, class: 'form-control input-lg', :placeholder => "475757575" %>
        </div>
      </div>
    </div>
    
  </div>

  <div class="col-md-3">
    <div class="form-group">
      <%= f.label :skype, "Votre Skype handle" %>
      <%= f.text_field :skype, class: 'form-control input-lg' %>
    </div>
  </div>
</div>
  
<p class="lead">Votre contribution</p>
  <div class="row">
    <div class="col-md-6">
    <div class="form-group">
      <%= f.label :skills, "Vos compétences" %>
      <%= f.text_field :skills, class: 'form-control input-lg' %>
    </div>
  </div>

  <div class="col-md-2">
    <div class="form-group">
      <%= f.label :contribution, "Votre cotisation" %>
      <div class="input-group"><%= f.text_field :contribution, class: 'form-control input-lg' %>
      <span class="input-group-addon">€</span></div>
    </div>
  </div>

  <div class="col-md-2">
    <div class="field form-group">
      <%= f.label :contribution_frequency, "fréquence" %>
      
      <%= f.select :contribution_frequency, @contribution_frequencies, {:selected => params[:contribution_frequency]}, {class: "form-control input-lg"} %>
    
    </div>
  </div>

    <!-- only from admin panel
    <div class="form-group">
      <%= f.label :total_contribution, "Votre contribution totale à ce jour" %>
      <%= f.text_field :total_contribution, class: 'form-control' %>
    </div>
  -->
  </div>
</div>
    
    
    

<br>

  <div class="form-actions col-md-6 col-md-offset-3">
    <div class="alert alert-warning alert-dismissable text-center">
      Rappel : remplissez tous les champs marqués d'un astérisque <span class="diasred"> (*)</span>.
    </div>
    <%= f.submit 'Modifier mon profil', :class => "btn btn-warning btn-lg btn-block" %>
  </div>
<% end %>

</div>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
	<div class="row profile">
		<div class="col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
    	 <div class="well profile">
            <div class="col-sm-12">
                <div class="col-xs-12 col-sm-8">
                    <h2><%= @user.name_or_fullname %></h2>

                    <!-- <p><strong>Membre : </strong> <%= @user.membership %></p>
                     <p><strong>Hobbies: </strong> Read, out with friends, listen to music, draw and learn new things. </p> -->
                    <p class="lead"><strong>Compétences : </strong><%= @user.skills %></span> </p>
                </div>             
                <div class="col-xs-12 col-sm-4 text-center">
                    <figure>
                        <p><%= image_tag @user.avatar.url(:medium), :class => "img-circle img-responsive" %></p>
                    </figure>
                </div>
            </div>            
            <div class="col-xs-12 divider text-center">
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong> <%= @user.contribution %> €</strong></h2>                    
                    <p><small><%= t("contribution_frequencies.#{@user.contribution_frequency}") %></small></p>
                   
                    
                </div>
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong>
                      <% if @user.total_contribution.present? %>
                      <%= @user.total_contribution %> 
                      <% else %>
                      0
                      <% end %>
                      €</strong></h2>                    
                    <p><small>Contribution totale</small></p>
                    
                </div>

                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong><%= @user.saldo %> €</strong></h2>                    
                    <p><small>solde contribution</small></p>
                    
                </div>
                <div class="col-xs-12 col-sm-6 emphasis">
                    <h2><strong><%= @user.following_projects_count %></strong></h2>                    
                    <p><small>Projets soutenus</small></p>
                </div>

                <div class="col-xs-12 col-sm-6 emphasis">
                    <h2><strong><%= @user.projects.count %></strong></h2>                    
                    <p><small>Projets proposés</small></p>
                </div>
              </div>

              <div class="col-xs-12 divider text-center">
              	<% if @user == current_user %> 
              		<div class="col-xs-12 col-sm-10 col-sm-offset-1 emphasis">
											<h2><%= link_to "Editer mon profil", edit_user_path, :class=> 'btn btn-warning btn-block' %></h2>
										</div>
								<% else %>
              		<div class="col-xs-12 col-sm-6 emphasis">
              		<h2>
											<% if current_user.following?(@user) %>
						          		<%= link_to "Ne plus suivre #{@user.name_or_fullname}", unfollow_user_path(@user), :class => 'btn btn-default btn-block' %>
						      		<% else %>
						      				<%= link_to "Suivre #{@user.name_or_fullname}", follow_user_path(@user), :class => 'btn btn-warning btn-block' %>
						      		<% end %>
									</h2>
              	</div>

              	<div class="col-xs-12 col-sm-6 emphasis">
              		<h2><%= link_to "Contacter #{@user.name_or_fullname}", "mailto:#{@user.email}", :class=> 'btn btn-info btn-block' %></h2>
              	</div>
              	<% end %>
	
              </div>
            </div>
    	 </div>                 
		</div>
	</div>

<div class="container">
<div class="page-header">
	<h1>Projets soutenus par <%= @user.name_or_fullname %></h1>
</div>
	<% if @user.following_projects.any? %>
	
	<div class="row">
      <ul class="thumbnails list-unstyled">
	<% @user.following_projects.each do |project| %>

		<li class="col-md-3">
          <div class="thumbnail" style="padding: 0">
            <div style="padding:4px">
              <%= image_tag project.cover.url(:medium) %>
            </div>
            <div class="caption">
              <p ><span class="lead"><%= link_to truncate(project.title, :length => 23), project %></span>
                <% if current_user == project.user %>
                <%= link_to edit_project_path(project) do %>
                  <%= content_tag(:i, " " ,:class=> 'fa fa-edit') -%>
                <% end %>
                <% end %>
              <br>par <%= link_to project.user.name_or_fullname, user_path(project.user) %></p>
              
              <p class="text-right"><i class="glyphicon glyphicon-map-marker"></i><%= project.pays %></p>
            </div>
            <div class="modal-footer" style="text-align: left">
              <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= project.funded_portion %>%;">
                    <!-- <span class="sr-only"><%= project.funded_portion %>% Complete</span> -->
                </div>
              </div>
              <div class="row text-center">
                <div class="col-md-4"><b><%= project.followers_count %></b><br/><small>contributeurs</small></div>
                <div class="col-md-4"><b><%= project.budget %> €</b><br/><small>requis</small></div>
                <div class="col-md-4">
                  <% if project.deadline && project.coming_deadline %>
                  <b><%= project.time_left_display %></b>
                    <br/><small>
                    
                  <% if project.time_left_in_days >= 30 %>
                      mois
                  <% elsif project.time_left_in_hours >= 72 %>
                      jours
                  <% elsif project.time_left_in_hours < 1 %>
                      minutes
                  <% else %>
                      heures
                  <% end %>
              <% else %>
              <b>clôturé</b>
              <% end %>
                  </small></div>
              </div>

              
        <br>
      <% if project.past_deadline %>
        <%= link_to "Période de contribution écoulée", "#", class: "btn btn-danger btn-block", :disabled => true %>
      <% else %>
        <% if current_user.following?(project) %>
          <%= link_to "Ne plus contribuer pour #{project.funding} €", unfollow_project_path(project), class: "btn btn-default btn-block" %>
            
        <% else %>
          <% if project.affordable(current_user) %>
            <%= link_to "Contribuer pour #{project.funding} €", follow_project_path(project), class: "btn btn-warning btn-block" %>
          <% else %>
            <%= link_to "Cotisez pour contribuer", "mailto:projetmbad@gmail.com", class: "btn btn-danger btn-block", :disabled => true %>
          <% end %>
          
        <% end %>
      <% end %>
         <!-- <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %> -->


            </div>
          </div>
        </li>

	<% end %>
</ul>
</div>

	<% else %>

	<h3 class="lead text-center"><%= @user.name_or_fullname %> ne soutient pas encore de projets.</h3>
	<% end %>





<!-- PROJETS PROPOSES PAR LE USER -->
<% if @user.projects.any? %>
<div class="page-header">
  <h1>Projets proposés par <%= @user.name_or_fullname %></h1>
</div>
  
  
  <div class="row">
      <ul class="thumbnails list-unstyled">
  <% @user.projects.each do |project| %>

    <li class="col-md-3">
          <div class="thumbnail" style="padding: 0">
            <div style="padding:4px">
              <%= image_tag project.cover.url(:medium) %>
            </div>
            <div class="caption">
              <p ><span class="lead"><%= link_to truncate(project.title, :length => 23), project %></span>
                <% if current_user == project.user %>
                <%= link_to edit_project_path(project) do %>
                  <%= content_tag(:i, " " ,:class=> 'fa fa-edit') -%>
                <% end %>
                <% end %>
              <br>par <%= link_to project.user.name_or_fullname, user_path(project.user) %></p>
              
              <p class="text-right"><i class="glyphicon glyphicon-map-marker"></i><%= project.pays %></p>
            </div>
            <div class="modal-footer" style="text-align: left">
              <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= project.funded_portion %>%;">
                    <!-- <span class="sr-only"><%= project.funded_portion %>% Complete</span> -->
                </div>
              </div>
              <div class="row text-center">
                <div class="col-md-4"><b><%= project.followers_count %></b><br/><small>contributeurs</small></div>
                <div class="col-md-4"><b><%= project.budget %> €</b><br/><small>requis</small></div>
                <div class="col-md-4">
                  <% if project.deadline && project.coming_deadline %>
                  <b><%= project.time_left_display %></b>
                    <br/><small>
                    
                  <% if project.time_left_in_days >= 30 %>
                      mois
                  <% elsif project.time_left_in_hours >= 72 %>
                      jours
                  <% elsif project.time_left_in_hours < 1 %>
                      minutes
                  <% else %>
                      heures
                  <% end %>
              <% else %>
              <b>clôturé</b>
              <% end %>
                  </small></div>
              </div>

              
        <br>
      <% if project.past_deadline %>
        <%= link_to "Période de contribution écoulée", "mailto:projetmbad@gmail.com", class: "btn btn-danger btn-block", :disabled => true %>
      <% else %>
        <% if current_user.following?(project) %>
          <%= link_to "Ne plus contribuer pour #{project.funding} €", unfollow_project_path(project), class: "btn btn-default btn-block" %>
            
        <% else %>
          <% if project.affordable(current_user) %>
            <%= link_to "Contribuer pour #{project.funding} €", follow_project_path(project), class: "btn btn-warning btn-block" %>
          <% else %>
            <%= link_to "Cotisez pour contribuer", "mailto:projetmbad@gmail.com", class: "btn btn-danger btn-block", :disabled => true %>
          <% end %>
          
        <% end %>
      <% end %>
         <!-- <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %> -->


            </div>
          </div>
        </li>

  <% end %>
</ul>
</div>

  <% end %>

</div>

</div>