config/routes.rb
Dias::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :projects
  

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  resources :users do
    member do
      get :follow
      get :unfollow
    end
  end

  resources :projects do
    member do
      get :follow
      get :unfollow
    end
  end
  

  get "about" => "pages#about"
  get "faq" => "pages#faq"
  get "team" => "pages#team"
  get "partners" => "pages#partners"
  get "manifesto" => "pages#manifesto"
  get "membership" => "pages#membership"
  get "fonctionnement" => "pages#fonctionnement"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@users = User.all
		@user = current_user
		@projects = Project.all
	end
end

app/views/home/index.html.erb
<% if signed_in? %>

  <div class="page-header">
  <h1>Les projets en cours
  <% if current_user.director %>
  <%= link_to "créer un nouveau projet", new_project_path, :class => "btn btn-warning btn-lg pull-right"  %>
  <% else %>
    <%= link_to "Suggérer un nouveau projet", "mailto:projetmbad@gmail.com", :class => "btn btn-warning btn-lg pull-right", :target => "_blank" %>
  <% end %>
  </h1>
</div>

    <%= render "projects/stream" %>
  


<% else %>

<div class="namefront text-center">Dias'</div>
  <div class="baseline text-center diasred">Pour une Afrique véritablement indépendante</div>
<!-- <h2 class="text-center">Soutenez des projets locaux de développement<br> directement et en quelques clics</h2> -->

<br><br>


<div class="container">  
      <p class="text-center"><%= link_to 'En savoir plus', about_path, :class => "btn btn-default btn-lg" %></p>
  
</div>
   

<!-- SIGNUP FORM -->
<div class="altbg-signup">

<div class="form-inline text-center">
        <p><%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>

          <div class="form-group">
            <%= f.email_field :email, :autofocus => true, :placeholder => "email", class: "form-control input-lg" %>
          </div>

          <div class="form-group">
            <%= f.password_field :password, :placeholder => "mot de passe", class: "form-control input-lg" %>
          </div>

          <div class="form-group">
            <%= f.password_field :password_confirmation, :placeholder => "confirmer mot de passe", class: "form-control input-lg" %>
          </div>

          <div class="form-group">
            <%= f.submit "S'inscrire à DIAS'", class: "btn btn-primary btn-lg" %>
          </div>
          <!-- <br><span class="center"><small><%= t("home.you_accept_terms") %><%= link_to t("home.our_terms"), "#" %>)</small></span> -->
        <% end %>
      </p>
      </div>

</div>

</div>


<!-- DISCOVER, VOTE, ACT -->
<div class="altbg-white">
  <div class="container">
<div class="row text-center">
	<h1 class="text-center">Comment ça marche ?</h1>
	<div class="col-md-4">
		<h2>Découvrez</h2>
		<p class="lead">Accédez à la liste des projets présélectionnés par l'association.  Les projets sont choisis pour leur sérieux et leur pertinence</p>

	</div>
	<div class="col-md-4">
		<h2>Participez</h2>
		<p class="lead">Participez à la concrétisation de projets de développement. Comment ? En allouant une participation à ceux qui vous touchent le plus selon le solde disponible de votre compte Dias'.</p>
	</div>
	<div class="col-md-4">
		<h2>Suivez</h2>
		<p class="lead">Recevez un rapport mensuel détaillé de l'évolution des projets et retrouvez-vous en première ligne lors de la recherche d’investisseurs.</p>
	</div>
</div>
</div>
</div>

<!-- FOOTER contact us -->

<div class="altbg-end">
<div class="container text-center">
  <p class="lead">Nous contacter :</p>
  <%= link_to "http://facebook.com/diasasbl", :class => 'btn btn-default btn-lg', :target => "_blank" do %>  
    <i class="fa fa-facebook fw"> Dias sur Facebook</i>
  <% end %>
  <%= link_to "mailto:projetmbad@gmail.com", :class => 'btn btn-default btn-lg', :target => "_blank" do %>  
    <i class="fa fa-envelope fw"> Email</i>
  <% end %>

  </div>
  </div>

  <p class="text-center"><br>Dias' asbl | tous droits réservés - 2014 <br><br>
     <%= link_to "Web developpement par UPcetera SPRL", "http://linkedin.com/in/laetitiamassa", :class => "btn btn-default btn-sm", :target => "_blank" %></p>

  <% end %>