config/routes.rb
Dias::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :projects
  

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  resources :users do
    member do
      get :follow
      get :unfollow
    end
  end

  resources :projects do
    member do
      get :follow
      get :unfollow
    end
  end
  

  get "about" => "pages#about"
  get "faq" => "pages#faq"
  get "team" => "pages#team"
  get "partners" => "pages#partners"
  get "manifesto" => "pages#manifesto"
  get "membership" => "pages#membership"
  get "fonctionnement" => "pages#fonctionnement"
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	acts_as_followable

  has_attached_file :cover, :styles => { :medium => "650x433#", :thumb => "300x200#" }, :default_url => ":style/missing_cover.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

	validates :funding, presence: true
	validates :budget, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :pays, presence: true
  validates :deadline, presence: true



	def total_funding
		contribution_per_head*followers_count
	end

	def contribution_per_head
		funding
	end

	def funded_portion
		total_funding*100/budget
	end

  def affordable(user)
    user.saldo >= self.funding 
  end

	def coming_deadline
    deadline && deadline >= Time.now
  end

  def past_deadline
    !coming_deadline
  end

  def time_left_display
    if time_left_in_days >= 30
      time_left_in_months
    elsif time_left_in_hours >= 72 
      time_left_in_days
    elsif ((deadline - Time.now) / 1.hour) < 1
      time_left_in_minutes
    else 
      time_left_in_hours
    end
  end

  def time_left_in_minutes
    ((deadline - Time.now) / 60).round
  end

  def time_left_in_hours
    ((deadline - Time.now) / 1.hour).round
  end

  def time_left_in_days
    ((deadline - Time.now) / 1.day).round
  end

  def time_left_in_months
    ((deadline - Time.now) / 1.month).round
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user, :only => [:edit, :update]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.order('id DESC')
    @project = current_user.projects.build if current_user
    @user = current_user
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @user = current_user
  end

  def follow
    @project = Project.find(params[:id])
    current_user.follow(@project)
    redirect_to :back, notice: "Merci de soutenir ce projet !"
  end

  def unfollow
    @project = Project.find(params[:id])
    current_user.stop_following(@project)
    redirect_to :back
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
    @user = current_user
  end

  # GET /projects/1/edit
  def edit
    @user = current_user
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)
    @user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path, notice: 'Felicitations, votre projet est publie !' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @user = current_user
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Votre projet a bien ete mis a jour' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def correct_user
      @project = current_user.projects.find_by(id: params[:id])
      redirect_to root_path, notice: "Vous ne pouvez pas modifier ce projet" if @project.nil?
    end

   

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description,
                                      :pays, :sector,
                                      :budget, :funding, :deadline,
                                      :cover, :link)
    end

  def markdown(content)
    markdown =Redcarpet::Markdown.new(Redcarpet::Render::XHTML,:hard_wrap=>true,:filter_html=>true,:autolink=>true,:no_intra_emphasis=>true)
    markdown.render(content).html_safe
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
	
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project, :url => project_path, :html => { :multipart => true }) do |f| %>
    <!-- <%= f.error_notification %> -->
    

  <div class="form-inputs">
    <div class="form-group">
      <%= f.label :title, "Titre du projet" %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :link, "Lien vers le projet" %>
      <%= f.text_field :link, :placeholder => "http://...", class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :cover, "Illustration du projet" %>
      <%= f.file_field :cover, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Description du projet" %>
      <%= f.text_area :description, rows: "7", class: 'form-control' %>
    </div>
<div class="row">
    <div class="form-group col-md-6">
      <%= f.label :pays, "Pays où sera réalisé le projet" %>
      <%= f.text_field :pays, class: 'form-control' %>
    </div>
    
    <div class="form-group col-md-6">
      <%= f.label :sector, "Secteur" %>
      <%= f.text_field :sector, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :budget, "Montant total à financer" %>
      <div class="input-group"><%= f.text_field :budget, class: 'form-control' %><span class="input-group-addon">€</span></div>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :funding, "Contribution individuelle demandée" %>
      <div class="input-group"><%= f.text_field :funding, class: 'form-control' %><span class="input-group-addon">€ / contributeur</span></div>
    </div>
  </div>

    <div class="form-group">
      <%= f.label :deadline, "Date limite de contribution" %>
      <%= f.datetime_select :deadline, class: 'form-control input-lg' %>
    </div>

  </div>

  <div class="form-actions">
    <%= f.submit "Modifier le projet", class: "btn btn-warning btn-lg" %>
  </div>
<% end %>

app/views/projects/_stream.html.erb
<div class="row">
      <ul class="thumbnails list-unstyled">
<% @projects.each do |project| %>

  
        <li class="col-md-3">
          <div class="thumbnail" style="padding: 0">
            <div style="padding:4px">
              <%= image_tag project.cover.url(:medium) %>
            </div>
            <div class="caption">
              <p ><span class="lead"><%= link_to truncate(project.title, :length => 23), project %></span>
                <% if current_user == project.user %><%= link_to edit_project_path(project) do %>
                  <%= content_tag(:i, " " ,:class=> 'fa fa-edit') -%>
                <% end %>
                <% end %>
              <br>par <%= link_to project.user.name_or_fullname, user_path(project.user) %></p>
              
              <p class="text-right">
                <i class="glyphicon glyphicon-map-marker"></i><%= project.pays %>
                <br><i class="glyphicon glyphicon-cog"></i> <%= project.sector %></p>
            </div>
            <div class="modal-footer" style="text-align: left">
              <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= project.funded_portion %>%;">
                    <!-- <span class="sr-only"><%= project.funded_portion %>% Complete</span> -->
                </div>
              </div>
              <div class="row text-center">
                <div class="col-md-4"><b><%= project.followers_count %></b><br/><small>contributeurs</small></div>
                <div class="col-md-4"><b><%= project.budget %> €</b><br/><small>requis</small></div>
                <div class="col-md-4">
                  <% if project.deadline && project.coming_deadline %>
                  <b><%= project.time_left_display %></b>
                    <br/><small>
                    
                  <% if project.time_left_in_days >= 30 %>
                      mois
                  <% elsif project.time_left_in_hours >= 72 %>
                      jours
                  <% elsif project.time_left_in_hours < 1 %>
                      minutes
                  <% else %>
                      heures
                  <% end %>
              <% else %>
              <b>clôturé</b>
              <% end %>
                  </small></div>
              </div>

              
        <br>
      <% if project.past_deadline %>
        <%= link_to "Période de contribution écoulée", "mailto:projetmbad@gmail.com", class: "btn btn-danger btn-block", :disabled => true %>
      <% else %>
        <% if current_user.following?(project) %>
          <%= link_to "Ne plus contribuer pour #{project.funding} €", unfollow_project_path(project), class: "btn btn-default btn-block" %>
            
        <% else %>
          <% if project.affordable(current_user) %>
            <%= link_to "Contribuer pour #{project.funding} €", follow_project_path(project), class: "btn btn-warning btn-block" %>
          <% else %>
            <%= link_to "Cotisez pour contribuer", "mailto:projetmbad@gmail.com", class: "btn btn-danger btn-block", :disabled => true %>
          <% end %>
          
        <% end %>
      <% end %>
         <!-- <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %> -->


            </div>
          </div>
        </li>


     
        
      

    <% end %>

</ul>
</div>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Editez votre projet</h1>
</div>

<div class="col-md-2">
<div class="alert alert-info alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <p><strong>Attention !</strong> Tous les champs doivent être remplis</p>
</div>
</div>

<div class="col-md-8">

<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<%= render "projects/stream" %>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>Créer un nouveau projet</h1>
</div>

<div class="col-md-2">
<div class="alert alert-info alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <p><strong>Attention !</strong> Tous les champs doivent être remplis</p>
</div>
</div>

<div class="col-md-8">
<%= simple_form_for(@project, :url => projects_path, :html => { :multipart => true }) do |f| %>

  <!-- <%= f.error_notification %> -->

  <div class="form-inputs">
  	<div class="form-group">
      <%= f.label :title, "Titre du projet" %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :link, "Lien vers le projet" %>
      <%= f.text_field :link, :placeholder => "http://...", class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :cover, "Illustration du projet" %>
      <%= f.file_field :cover, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Description du projet" %>
      <%= f.text_area :description, rows: "7", class: 'form-control' %>
    </div>
<div class="row">
    <div class="form-group col-md-6">
      <%= f.label :pays, "Pays où sera réalisé le projet" %>
      <%= f.text_field :pays, class: 'form-control' %>
    </div>
  	
  	<div class="form-group col-md-6">
      <%= f.label :sector, "Secteur" %>
      <%= f.text_field :sector, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :budget, "Montant total à financer" %>
      <div class="input-group"><%= f.text_field :budget, class: 'form-control' %><span class="input-group-addon">€</span></div>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :funding, "Contribution individuelle demandée" %>
      <div class="input-group"><%= f.text_field :funding, class: 'form-control' %><span class="input-group-addon">€ / contributeur</span></div>
    </div>
  </div>

    <div class="form-group">
      <%= f.label :deadline, "Date limite de contribution" %>
      <%= f.datetime_select :deadline, class: 'form-control input-lg' %>
    </div>

  </div>

  <div class="form-actions">
    <%= f.submit "Créer le projet", class: "btn btn-warning btn-lg" %>
  </div>
<% end %>

</div>

app/views/projects/show.html.erb
<div class="page-header">
  <h1><%= @project.title %>
  <small><% if current_user == @project.user %>
  	<%= link_to edit_project_path(@project) do %>
                  <%= content_tag(:i, " " ,:class=> 'fa fa-edit') -%>
                <% end %>
                <% end %></small></h1>
</div>


<div class="row">

<% if !current_user.nonvalidated %>
 <div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <h2 class="text-center">
  	<strong>Attention !</strong>
  	<br>Seuls les membres validés ont accès au détail des projets.
  	<br><small> Votre inscription est actuellement en cours de validation par l'équipe Dias'.
	<br>Pour plus d'info, contactez-nous via <%=link_to "projetmbad@gmail.com", "mailto:projetmbad@gmail.com" %></small></h2>
</div>
<% else %>



	

	<div class= "col-md-7">
		<p><%= image_tag @project.cover.url(:medium), class: "img-rounded" %></p>
		
		<div class="jumbotron">
      <h5 class="text-right"><i class="glyphicon glyphicon-map-marker"></i> <%= @project.pays %>
        </h5>
      <h5 class="text-right"><i class="glyphicon glyphicon-cog"></i> <%= @project.sector %></h5>
			<h3>Description du projet
      <%= link_to @project.link, :target => "_blank" do %>
        <%= content_tag(:i, " En savoir plus sur ce projet", :class=> 'fa fa-info-circle btn btn-default pull-right') if @project.link.present? -%>
      <% end %>   
      </h3>
  		<p class="smaller"><%= simple_format(@project.description) %></p>
		</div>
	</div>



<div class="col-md-5">


	<div class="jumbotron text-center">

		<h3><i class="glyphicon glyphicon-user pull-left"></i> <%= @project.followers_count %> 
		<br><small>contributeurs</small></h3>

		<div class="divider">
			<h3><i class="glyphicon glyphicon-euro pull-left"></i> <%= @project.total_funding %> € 
			<br><small> récoltés sur <%= @project.budget %> € requis</small></h3>
			<div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= @project.funded_portion %>%;">
                    <!-- <span class="sr-only"><%= @project.funded_portion %>% Complete</span> -->
                </div>
              </div>
		</div>

		<div class="divider">
			<% if @project.deadline && @project.coming_deadline %>
                  <h3><i class="glyphicon glyphicon-time pull-left"></i> <%= @project.time_left_display %>
                    <small>
                    
                  <% if @project.time_left_in_days >= 30 %>
                      mois restant
                  <% elsif @project.time_left_in_hours >= 72 %>
                      jours restant
                  <% elsif @project.time_left_in_hours < 1 %>
                      minutes restant
                  <% else %>
                      heures restant</h3>
                  <% end %>
              <% else %>
              <h3><i class="glyphicon glyphicon-time pull-left"></i> La collecte est clôturée</h3>
              <% end %>
		</div>

 		<div class="divider"> 
			<h3>
			<% if @project.past_deadline %>
        <%= link_to "Période de contribution écoulée", "mailto:projetmbad@gmail.com", class: "btn btn-danger btn-lg btn-block", :disabled => true %>
      <% else %>
				<% if current_user.following?(@project) %>
          <%= link_to "Ne plus contribuer pour #{@project.funding} €", unfollow_project_path(@project), class: "btn btn-default btn-lg btn-block" %>
            
        <% else %>
        	<% if @project.affordable(current_user) %>
          	<%= link_to "Contribuer pour #{@project.funding} €", follow_project_path(@project), class: "btn btn-warning btn-lg btn-block" %>
          <% else %>
          	<%= link_to "Cotisez pour contribuer", "mailto:projetmbad@gmail.com", class: "btn btn-danger btn-lg btn-block", :disabled => true %>
          <% end %>
          
        <% end %>
      <% end %>
      </h3>
    </div>

  </div> <!-- fin jumbotron basic data -->
     



<div class="jumbotron">

<div class="row">
			
      
      <div class="col-xs-12 col-sm-8">
      	<h3>Auteur du projet</h3>
				<h4><%= link_to @project.user.name_or_fullname, user_path(@project.user) %>
				<br><small><%= @project.user.pays %></small></h4>
			</div>

			<div class="col-xs-12 col-sm-4 text-center">
        <%= image_tag @project.user.avatar.url(:thumb), :class => "img-circle img-responsive" %>
      </div>
		</div>
 </div>

<div class="jumbotron">
	<h3>Contributeurs au projet</h3>


	<% if @project.followers.any? %>
	<ul class="list-unstyled">
	<% @project.followers.each do |backer| %>

	<li>
		<p>
			<div class="row">
			<div class="col-xs-12 col-sm-3 text-center">
			
                        <%= image_tag backer.avatar.url(:thumb), :class => "img-circle img-responsive" %>
                        
                    
                  </div>
                  <div class="col-xs-12 col-sm-9">
			<h4><%= link_to backer.name_or_fullname, user_path(backer) %>
				<br><small><%= backer.pays %></small></h4>
		</div>
	</div>
		</p>
	</li>

	<% end %>

</ul>
	<% end %>

	</div>
	
</div>

<% end %>
</div>