config/routes.rb
Dias::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :projects
  

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  resources :users do
    member do
      get :follow
      get :unfollow
    end
  end

  resources :projects do
    member do
      get :follow
      get :unfollow
    end
  end
  

  get "about" => "pages#about"
  get "faq" => "pages#faq"
  get "team" => "pages#team"
  get "partners" => "pages#partners"
  get "manifesto" => "pages#manifesto"
  get "membership" => "pages#membership"
  get "fonctionnement" => "pages#fonctionnement"
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Dias'", root_path, class: 'navbar-brand bigger diasfont' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
	
  
  <li><%= link_to 'Accueil', root_path %></li>
  <li><%= link_to 'A propos', about_path %></li>
  <li><%= link_to 'FAQ', faq_path %></li>
  <li><%= link_to 'Fonctionnement', fonctionnement_path %></li>
  <li><%= link_to 'Manifeste', manifesto_path %></li>

  <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name_or_fullname if @user.present? %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Consultez votre profil', user_path(current_user) %></li>
            <li><%= link_to 'Editez votre profil', edit_user_path(current_user) %></li>

            <% if current_user.director %>
            <li role="presentation" class="divider"></li>
            <li><%= link_to 'Administration', admin_users_path %></li>
            <% end %>

            <li role="presentation" class="divider"></li>
            <li><%= link_to 'Votre compte', edit_user_registration_path %></li>

            <li role="presentation" class="divider"></li>
              <li><%= link_to 'Déconnexion', destroy_user_session_path, :method=>'delete' %></li>
          </ul>
  </li>

<% else %>
  <li class="big"><%= link_to 'Accueil', root_path %></li>
  <li class="big"><%= link_to 'A propos', about_path %></li>
  <li class="big"><%= link_to 'FAQ', faq_path %></li>
  <li class="big"><%= link_to 'Fonctionnement', fonctionnement_path %></li>
  <li class="big"><%= link_to 'Manifeste', manifesto_path %></li>
  <li class="big"><%= link_to 'Connexion', new_user_session_path %></li>
  <li class="big"><%= link_to 'Inscription', new_user_registration_path %></li>
<% end %>

app/views/layouts/_nonvalidated.html.erb
<div class="alert alert-warning alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <p class="text-center"><strong>Attention !</strong> Votre inscription est en cours de validation par l'équipe Dias'.
  	<br><b>Seuls les profils dûment complètés sont examinés pour validation</b>
	<br>Pour plus d'info, contactez-nous via <%=link_to "projetmbad@gmail.com", "mailto:projetmbad@gmail.com" %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dias' - solution pour une Afrique indépendante" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Dias" %>">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <% if user_signed_in? %>
       <div class="container">
         <%= render 'layouts/messages' %>
       </div>
          <div class="container">
            <% if current_user.nonvalidated %><%= render 'layouts/nonvalidated' %><% end %>
            <%= yield %>
          </div>
        
        <% else %>
           <div class="container">
              <%= render 'layouts/messages' %>
          </div>
          <%= yield %>
          <% end %>

     </div>
    </main>

    <!-- GOOGLE ANALYTICS -->

    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52373443-1', 'auto');
  ga('send', 'pageview');

</script>
  </body>
</html>